import { createPublicClient } from '@/lib/supabase/public';
import MenuPageClient from '@/components/menu-page-client';
import type { MenuCategory } from '@/components/menu-page-client';

/**
 * The menu was fully dynamic, so all three queries below ran on every single
 * page view for content that changes a few times a year — latency on the site's
 * most-visited page, and Supabase quota spent re-fetching identical rows.
 *
 * It is cached for an hour instead. Edits do not wait for that window: every
 * write in /api/admin/menu calls revalidatePath('/menu'), so a dish saved in
 * the admin panel is live immediately. The hour is only the backstop for
 * changes made directly in the Supabase dashboard.
 */
export const revalidate = 3600;

/**
 * Point a dish at its plated photograph.
 *
 * Supabase stores the path to the original cut-out under
 * `Menu/KS Menu Webp/...`. Those are RGBA silhouettes on a transparent ground -
 * the floating-dish source material the client rejected. `menu-plated/` holds
 * the same dishes composited onto a warm ground with a contact shadow and
 * normalised framing (generated by scratchpad/plate.py; re-runnable).
 *
 * Rewritten here rather than in the database so the originals stay the record
 * of what was uploaded, and so the admin panel's upload flow is untouched. A
 * path that does not match the expected prefix is passed through unchanged, so
 * a newly uploaded dish still renders - just without the plating until the
 * script is re-run over it.
 */
const PLATED_FROM = '/assets/Menu/KS Menu Webp/';
const PLATED_TO = '/assets/menu-plated/';

function platedSrc(src: string): string {
    return src.startsWith(PLATED_FROM) ? src.replace(PLATED_FROM, PLATED_TO) : src;
}

export default async function MenuPage() {
    const supabase = createPublicClient();

    const [
        { data: categories },
        { data: items },
        { data: addOns },
    ] = await Promise.all([
        supabase.from('menu_categories').select('*').order('sort_order'),
        supabase.from('menu_items').select('*').order('sort_order'),
        supabase.from('menu_category_addons').select('*'),
    ]);

    const menuData: MenuCategory[] = (categories || []).map(cat => ({
        id: cat.id,
        name: cat.name,
        addOns: (addOns || [])
            .filter(a => a.category_id === cat.id)
            .map(a => ({ title: a.title, price: a.price })),
        items: (items || [])
            .filter(item => item.category_id === cat.id)
            .map(item => ({
                number: item.item_number,
                title: item.title,
                imageSrc: platedSrc(item.image_src || ''),
                price: item.price,
                groupPrice: item.group_price || undefined,
                portionNote: item.portion_note || undefined,
                description: item.description || '',
                badges: item.badges || [],
                addOnNote: item.add_on_note || undefined,
                angled: item.angled || false,
            })),
    })).filter(cat => cat.items.length > 0 || cat.addOns?.length);

    return <MenuPageClient categories={menuData} />;
}
